name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'pnpm'
      - run: pnpm ci
      - run: pnpm run build --if-present
      - run: pnpm test
